# Debug Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Voir où Spring cherche les fichiers
logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.thymeleaf=TRACE
# Upload
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8082
serpapi.key=8cc7226aa51581da4209e23fc5ed81e1b230cac2248f60ae2fbb3fde0831719e
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:liasdb
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.mode=HTML